baseurl = "https://mari-knitbear.netlify.app/"
languageCode = "ja-jp"
defaultContentLanguage = "en"
title = "Knit Bear Mary"
theme = "dream"

copyright = "Mary Satoh"

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

# hasCJKLanguage = true

[params]
  background = "#d4ffca"
  # backgroundImage = "/img/background.png"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  # backgroundDark = "black"
  # backgroundImageDark = "/me/background-dark.jpg"
  # darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  author = "Mary Satoh"
  description = "Bear"
  avatar = "/img/avatar.jpg"
  headerTitle = "すてきなものたち"
  motto = "気に入っているすてきなもの、かぎ針や裁縫による自分の作品"
  # categoriesLimitInHeader = 6 # deprecated
  headerBottomText = "サイトの説明などを入れられます" # deprecated

  footerBottomText = "サイトの説明などを入れられます"

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "satohmary@gmail.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2021

  favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  [params.advanced]
    customCSS = ["css/custom.css"]
  #   customJS = []
